export const templates = {
    happy: [
      `Your joy is contagious. Keep spreading light.`,
      `Happiness has been your superpower this month.`,
      `A happy moment is a precious gem to be cherished.`,
      `Find joy in the ordinary.`,
      `The world is a happier place with you in it.`,
      `Let your smile change the world, but don't let the world change your smile.`,
      `Every day may not be good, but there's something good in every day.`,
      `Happiness is a journey, not a destination.`,
      `Joy is the simplest form of gratitude.`,
      `The sun always shines brightest after the rain.`,
      `Choose to be optimistic, it feels better.`,
      `Your happiness is a beautiful work of art.`,
      `Be happy for this moment. This moment is your life.`,
      `The best way to cheer yourself is to cheer someone else up.`,
      `Life is short. Smile while you still have teeth.`,
      `It's a beautiful day to be happy.`,
      `May your day be filled with happy moments.`,
      `Happiness is an inside job.`,
      `The secret to happiness is freedom, the secret to freedom is courage.`,
      `Every moment is a fresh beginning.`,
      `Don't cry because it's over, smile because it happened.`,
      `A good laugh is sunshine in the house.`,
      `The most important thing is to enjoy your life—to be happy—it's all that matters.`,
      `Let us be grateful to people who make us happy; they are the charming gardeners who make our souls blossom.`,
      `Happiness is not something ready made. It comes from your own actions.`,
      `If you want to be happy, be.`,
      `The best feeling in the world is a happy heart.`,
      `Your life is your message to the world. Make sure it's inspiring.`,
      `Joy is not in things; it is in us.`,
      `Happiness is when what you think, what you say, and what you do are in harmony.`,
      `The purpose of our lives is to be happy.`,
      `Count your blessings, not your problems.`,
      `The smallest things can bring the greatest joy.`,
      `Stay positive, happy thoughts.`,
      `Happiness is found in the simple things.`,
      `May your day be as bright as your smile.`,
      `Radiate positivity and joy.`,
      `Your positive energy is a gift to the world.`,
    ],
    sad: [
      `Even the clouds make way for sunlight. Hang in there.`,
      `Your strength shows even in quiet sadness.`,
      `It's okay to not be okay.`,
      `Sadness is a temporary state, not a permanent home.`,
      `Healing doesn't mean the damage never existed. It means the damage no longer controls our lives.`,
      `The best way out is always through.`,
      `What you feel is valid. Allow yourself to feel it.`,
      `Tough times don't last, but tough people do.`,
      `There is no greater sorrow than to recall in misery the time when we were happy.`,
      `Grief is the price we pay for love.`,
      `A sad soul needs a hug more than advice.`,
      `In the midst of winter, I found there was, within me, an invincible summer.`,
      `The pain you feel today is the strength you feel tomorrow.`,
      `A good cry can cleanse the soul.`,
      `The sun will rise again.`,
      `Every tear is a sign of life.`,
      `You are not alone in this.`,
      `This too shall pass.`,
      `Let your tears water the seeds of your future.`,
      `It's okay to feel sad, but remember to let it go.`,
      `Sadness flies away on the wings of time.`,
      `Give yourself the grace to be human.`,
      `Healing is an art. It takes time, it takes practice. It takes love.`,
      `The darkest hour is just before the dawn.`,
      `Your emotions are a part of your journey, not your destination.`,
      `Breathe. Let go. And remind yourself that this very moment is the only one you know you have for sure.`,
      `Sometimes the best thing you can do is not think, not wonder, not imagine, not obsess. Just breathe, and have faith that everything will work out for the best.`,
      `Pain is inevitable. Suffering is optional.`,
      `It's okay to take a moment for yourself.`,
      `Your resilience is stronger than your sadness.`,
      `There is a crack in everything, that's how the light gets in.`,
      `May you find comfort in the stillness.`,
      `Find strength in your vulnerability.`,
      `Your sadness does not define you.`,
      `A new beginning is just around the corner.`,
      `Hope is the one thing that can't be taken from you.`,
    ],
    neutral: [
      `Still waters run deep — and so do you.`,
      `Your calm is a quiet kind of courage.`,
      `The art of living is in the balance.`,
      `Breathe in, breathe out.`,
      `Find peace in the present moment.`,
      `Be present in all things and thankful for all things.`,
      `Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow. Let reality be reality.`,
      `Mindfulness is the gentle practice of being here now.`,
      `The journey of a thousand miles begins with a single step.`,
      `Everything in its own time.`,
      `Peace begins with a smile.`,
      `Simplicity is the ultimate sophistication.`,
      `Go with the flow.`,
      `The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.`,
      `Don't rush to be a different person. Just be who you are and let the changes happen naturally.`,
      `Find your rhythm and let it guide you.`,
      `Embrace the quiet.`,
      `You are exactly where you need to be.`,
      `The essence of all beautiful art is beautiful thought.`,
      `Live in the moment, for the future is not promised.`,
      `A little progress each day adds up to big results.`,
      `It is what it is.`,
      `Be patient with yourself. Nothing in nature blooms all year.`,
      `The art of stillness is a gentle strength.`,
      `Find the beauty in the mundane.`,
      `The only moment we have is now.`,
      `Observe your thoughts, but don't get lost in them.`,
      `Just be.`,
      `Let go of what you can't control.`,
      `Peace is the result of retraining your mind to process life as it is, rather than as you think it should be.`,
      `Nothing is permanent, so cherish the good and let go of the bad.`,
      `Find your center.`,
      `Today is a fresh page.`,
      `Everything is connected.`,
      `A quiet mind is a powerful mind.`,
      `Let your actions speak louder than your words.`,
      `The simple things are the most profound.`,
    ],
    angry: [
      `Anger is a message, not a mistake. Listen to it.`,
      `Don't let your mind be a prison for your anger. Find a release.`,
      `For every minute you are angry you lose sixty seconds of happiness.`,
      `Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else; you are the one who gets burned.`,
      `Anger is a condition in which the tongue works faster than the mind.`,
      `Breathe. Let go. And remind yourself that this moment is temporary.`,
      `Anger is a storm that soon passes, leaving a clear sky.`,
      `The best remedy for a short temper is a long walk.`,
      `Speak when you are angry, and you will make the best speech you will ever regret.`,
      `Anger is an acid that can do more harm to the vessel in which it is stored than to anything on which it is poured.`,
      `A moment of patience in a moment of anger prevents a thousand moments of sorrow.`,
      `Turn your anger into motivation.`,
      `Don't allow a day of anger to become a lifetime of regret.`,
      `Use your frustration as fuel to build something better.`,
      `Anger is just a feeling, not a command.`,
      `You have the power to choose your reaction.`,
      `Take a step back. Re-evaluate.`,
      `Control your anger, don't let it control you.`,
      `Anger is a warning sign. Listen to what it's trying to tell you.`,
      `Your inner peace is worth more than a moment of rage.`,
      `Before you speak, think. Is it true? Is it helpful? Is it kind? Is it necessary?`,
      `Channel your energy into a positive change.`,
      `Don't let yesterday's frustrations ruin today.`,
      `Be mindful of your reaction.`,
      `Every moment of anger is a missed opportunity for peace.`,
      `Anger, if not restrained, is frequently more hurtful than the injury that provokes it.`,
      `Patience is the cure for anger.`,
      `The more you are in a state of gratitude, the less you are in a state of anger.`,
      `Your inner peace is your greatest asset.`,
      `Don't let your anger become a barrier.`,
      `Let your frustration fuel your progress.`,
      `Find a constructive outlet for your emotions.`,
      `Anger can be a great motivator, but only if you direct it toward a positive goal.`,
      `In every moment of anger, there is a choice to find calm.`,
      `Your peace of mind is more valuable than winning an argument.`,
      `Reacting in anger will only lead to more anger.`,
      `Let go of the need to be right.`,
    ]
};
